server:
  compression:
    enabled: true
  port: 6060

management:
  server:
    port: 6061

spring:
  application:
    name: projectbasic
  datasource:
    url: jdbc:h2:~/${spring.application.name}.db
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update

app:
  openapi:
    info:
      title: ${spring.application.name}
      description: ${spring.application.name}
    components:
      securitySchemes:
        admin:
          type: APIKEY
          name: Authorization
          in: HEADER